import { Inter } from "next/font/google";
import "./globals.css";

// header UI Components
import Header from "./header/header";
import Contact from "./contact/page";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />

       

        {children}
      </body>
    </html>
  );
}
